### ISSUE TITLE
Abstract common sink values

### ISSUE THREAD

**Issue by chrisjohnson** [chrisjohnson/azure-key-vault-agent#10]
Being able to abstract some common sink values (like `vaultBaseURL`) seems handy when defining multiple sinks.

I had the thought to add some `sinkDefaults` key and then the configparser would just merge it into each sink. However I'm wondering if the golang yaml lib we are using supports yaml anchors out of the box. That would let us do something like this:

```yaml
defaults:
  &defaults
  vaultBaseURL: https://cjohnson-kv.vault.azure.net

sinks:
 - <<: *defaults
    name: test
    etc: whatever
```

(or whatever the syntax is)
