### ISSUE TITLE
Two paths for Certificate objects

### ISSUE THREAD

**Issue by grep-ir** [chrisjohnson/azure-key-vault-agent#26]
We will need two support writing out the private key and certificate to distinct file paths.

**Comment by chrisjohnson** [comment]
We need to investigate how the azure API expects you to get the key in an uncombined format, and then probably the answer will just be to add a second sink config block that points to that endpoint directly.

We may need to add some auto-discovery mechanism e.g.

```yaml
sinks:
  - kind: cert
    name: test
    path: foo.crt
  - kind: key
    fromCert: test
    path: foo.key
```

And then it looks up the key by first looking up the cert to discover the key id.

If azure just makes them always have the same name then we can probably skip the discovery mechanism and just do it like this:

```yaml
sinks:
  - kind: cert
    name: test
    path: foo.crt
  - kind: key
    name: test
    path: foo.key
```

TODO: Investigate whether or not azure names the key/secret the same as the cert every time
TODO: Investigate whether azure then prevents you from making a standalone key/secret with the same name as the cert
